environment:
  name: prod
  project: cdf-bootcamp-21-prod # ex. cdf-bootcamp-01-prod
  type: prod # prod, staging, dev, test, qa
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-21-prod # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env

      # Groups
      # OBJECT ID FOR test/prod Groups
      data_developer_source_id: 9ff8686c-0495-4c9a-8a59-aeb7283c6764 # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      data_pipeline_oee_source_id: 19893e25-a9a1-4ad6-8aa5-a5fa0d1a4d1a # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      readwrite_source_id: 25a767b8-8349-45bf-9fde-5eeccaa62316 # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      icapi_extractors_source_id: 3b48ea5e-a007-4b3b-b831-f76102c1dc84 # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx

      # Client Ids (App registrations or Service Principals)
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      oee_space_name: oee_ts_space 
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee

